### PR TITLE
feat: Replaced kapa.ai with Cookbook Onboard (AI Assistant)

### PR DESCRIPTION
**Pull request by ClockRide**
## Preview
Preview link: https://wormhole-docs-cookbook.vercel.app

## Ask Cookbook AI Assistant
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Wormhole resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about using Wormhole, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.

Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Wormhole-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

image

### CODE REVIEW

**Comment by eshaben** [comment]
Hey @ClockRide! Thanks for opening the PR! 💜 I'll take a look at this today!

**Comment by evgeniko** [comment]
Could we keep the old button location please?

**Comment by ClockRide** [comment]
> I noticed that the button currently loads after the page is fully loaded, which is particularly noticeable in the header due to the shifting content. Once it's moved out of the header, this won't be an issue. However, I'm curious why it's loading in the body instead of the header, especially since `block libs` typically handles rendering JavaScript in the header. Is this something that's configurable? It definitely works as is, but I'm asking just to better understand 🙂

That’s the case because we have the "defer" attribute in the script tag that loads our integration. We’ve added it to ensure we don’t impact your website’s load time, even if it introduces a slight delay in loading the chatbot. Happy to swap it for "async" though if you’d prefer to load it asynchronously instead of after the web page is loaded, but this might result in worse page load times on devices with low internet bandwidth. 

That’s the [code snippet](https://github.com/papermoonio/wormhole-mkdocs/pull/71/files#diff-1632ed8257a41f38dd75eb254f77b26ee13443ae895b24aa4305201d38d6b6e6R41) I’m talking about, by the way:

```html
<script defer src="https://cdn.jsdelivr.net/npm/@cookbookdev/docsbot/dist/standalone/index.cjs.js"></script>
```

As far as rendering the script in the body goes, that’s a good point—thanks! My guess is that the <div> tag we put in the head makes browsers move it and everything after it to the body of the page. In the raw HTML layout, both the div and script tags are in the head section, but in Chrome DevTools they are not. Anyway, it should be fixed now, and I made sure to squash my changes to keep it clean. Also moved the button to where you had it before (cc @evgeniko)

Let me know if there are any more questions or requests :)​

**Comment by ClockRide** [comment]
> I noticed that the button currently loads after the page is fully loaded, which is particularly noticeable in the header due to the shifting content. Once it's moved out of the header, this won't be an issue. However, I'm curious why it's loading in the body instead of the header, especially since `block libs` typically handles rendering JavaScript in the header. Is this something that's configurable? It definitely works as is, but I'm asking just to better understand 🙂

By the way, the button position can be adjusted in the future through the portal you should already have access to. It's adjustable at [cms.cookbook.dev](https://cms.cookbook.dev) > Bot Configuration (in the header) > Appearance (in the sidebar).

**Comment by eshaben** [comment]
Thanks for the responses! No need to change it to async; I was just curious 🙂 

@evgeniko I'll merge this into a local branch and play around with the styling to align it with the mockup I received from the Sp-ce team. So once I get that completed, I'll open up a new PR there and request your review

**Pull request merged**
